on:
  push:
  schedule:
    - cron: 0 20 * * *
jobs:
  jbang:
    runs-on: ubuntu-latest
    name: A job to run jbang
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /root/.jbang
          key: $-jbang-$
          restore-keys: |
            $-jbang-
      - name: Credfile
        run: |
          echo ${{ secrets.ENV_GOOGLE_CALENDAR_FILE }} | base64 -d > .cred.google
          echo ${{ secrets.BEVY_MULE_SYNC_PROPS }} | base64 -d > mulesync.properties
      - name: jbang
        uses: jbangdev/jbang-action@v0.86.0
        with:
          script: BevyGoogleCalendarSync.java
          scriptargs: "mulesync.properties"
        env:
          JBANG_REPO: /root/.jbang/repository
          GITHUB_TOKEN: $
      - name: CredfileClear
        run: |
          rm .cred.google
          rm mulesync.properties